### ISSUE TITLE
Define the TrafficMetrics CRD

### ISSUE THREAD

**Issue by surajssd** [servicemeshinterface/smi-sdk-go#16]
Here the TrafficMetrics CRD yaml file is just a placeholder add configs in this file.

https://github.com/deislabs/smi-sdk-go/blob/86042c47396f92f00ad451a030b498bb033277b3/crds/metrics.yaml

**Comment by stefanprodan** [comment]
The traffic metrics are an extension of the `APIService` not a CRD. We can't add the APIService yaml in this repo as it requires the CA bundle, see https://github.com/servicemeshinterface/smi-metrics/blob/master/chart/templates/apiservice.yaml
