### ISSUE TITLE
SMI conversion webhook

### ISSUE THREAD

**Issue by stefanprodan** [servicemeshinterface/smi-sdk-go#37]
SMI could provide a [conversion webhook](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/#webhook-conversion) that will automate the upgrade process of SMI custom resources. 

For example, the TrafficSplit v1alpha2 comes with a breaking change as the backend weight type changed from `resource.Quantity` to `int` in #24. The webhook would make the conversion between versions and update the TrafficSplit objects in-cluster without manual intervention by the cluster admins.

**Comment by grampelberg** [comment]
Big +1 from me. @stefanprodan do you think we should have this in place before we version the next API?

**Comment by stefanprodan** [comment]
@grampelberg to use the conversion webhook we have to switch to `apiextensions.k8s.io/v1` that means breaking compatibility with Kubernetes < 1.16 but most Kubernetes-asa-service are on 1.14...

**Comment by grampelberg** [comment]
Damnit k8s versioning ...
