### ISSUE TITLE
Mismatch between documentation and spec for Matches field

### ISSUE THREAD

**Issue by khhirani** [servicemeshinterface/smi-sdk-go#74]
I noticed that there is a discrepancy between the documentation for the Matches field and the spec for v1alpha3.

In the [documentation](https://github.com/servicemeshinterface/smi-spec/blob/master/apis/traffic-split/v1alpha3/traffic-split.md), the Matches field is underneath the `spec` field: 

> kind: TrafficSplit
> metadata:
>   name: ab-test
> spec:
>   service: website
>   matches:
>   - kind: HTTPRouteGroup
>     name: ab-test
>   backends:
>   - service: website-v1
>     weight: 0
>   - service: website-v2
>     weight: 100

But in the [spec](https://github.com/servicemeshinterface/smi-sdk-go/blob/master/pkg/apis/split/v1alpha3/traffic_split.go#L36-L43), the Matches field is defined underneath TrafficSplitBackend instead of TrafficSplitSpec.

I believe that the v1alpha3 spec should be updated to match the usage described in the documentation.

**Comment by bharaththiruveedula** [comment]
@khhirani can I assign this to myself?

**Comment by khhirani** [comment]
@bharaththiruveedula Sure
