### ISSUE TITLE
v1alpha3 TrafficSpec object does not have expected Matches field

### ISSUE THREAD

**Issue by ksubrmnn** [servicemeshinterface/smi-sdk-go#77]
Why are the [matches](https://github.com/servicemeshinterface/smi-sdk-go/blob/master/pkg/apis/split/v1alpha3/traffic_split.go#L42) for TrafficSplit in TrafficSplitBackend and not TrafficSplitSpec? My understanding from the [documentation](https://github.com/servicemeshinterface/smi-spec/blob/master/apis/traffic-split/v1alpha3/traffic-split.md) was that the TrafficSpecs would apply to all of the backends. Is that assumption incorrect? 

Also is there a reason the type is different than Matches for [TrafficTarget](https://github.com/servicemeshinterface/smi-sdk-go/blob/9eebc8ce575d5fecdc46b7a1344eed4b2d6e4ca6/pkg/apis/access/v1alpha1/traffic_target.go#L42)? Will the TrafficTarget Matches type change in future iterations?

**Comment by ksubrmnn** [comment]
@michelleN @stefanprodan

**Comment by stefanprodan** [comment]
fixed in #76

**Comment by ksubrmnn** [comment]
@stefanprodan When will this change be included in a release?
