### ISSUE TITLE
v1alpha3 TrafficSpec Matches type is not the same as TrafficTarget Matches Type

### ISSUE THREAD

**Issue by ksubrmnn** [servicemeshinterface/smi-sdk-go#78]
Matches for [TrafficTarget](https://github.com/servicemeshinterface/smi-sdk-go/blob/9eebc8ce575d5fecdc46b7a1344eed4b2d6e4ca6/pkg/apis/access/v1alpha1/traffic_target.go#L42) is of type []string.

Matches for [TrafficSplit](https://github.com/servicemeshinterface/smi-sdk-go/blob/master/pkg/apis/split/v1alpha3/traffic_split.go#L36) is of type []corev1.TypedLocalObjectReference

The two types should match.

**Comment by ksubrmnn** [comment]
@michelleN @stefanprodan

**Comment by stefanprodan** [comment]
The name is the same but they represent different things, the TrafficSpec match points to a Kubernetes object while the TrafficTarget match points to a record inside a Kubernetes object.
