### ISSUE TITLE
Define a sample application

### ISSUE THREAD

**Issue by smarkm** [servicemeshinterface/smi-sdk-go#79]
Hi, Could we define a sample program? maybe just `*.yaml` resources, so that `SMI` providers can use it for testing, verifying and authenticating the implement,  maybe transplant the [Istio BookInfo app](https://istio.io/latest/docs/setup/getting-started/#bookinfo) is a good choise

**Comment by nveenjain** [comment]
Hi @smarkm , there is already an app we are trying to put in. It is very light weight collection of REST APIs, can be used to test service mesh of any type. 
Please take a look at https://github.com/layer5io/learn-layer5/, also we are working on SMI-conformance and using this app for that! Please join the discussion in #smi channel at http://slack.layer5.io/
