### ISSUE TITLE
Release 0.4.0 sdk

### ISSUE THREAD

**Issue by lachie83** [servicemeshinterface/smi-sdk-go#81]
We also need to tag 0.4.0 of the specification

**Comment by lachie83** [comment]
dep - https://github.com/servicemeshinterface/smi-sdk-go/pull/80

**Comment by michelleN** [comment]
v0.4.0 will reflect v0.5.0 of the specification

**Comment by michelleN** [comment]
https://github.com/servicemeshinterface/smi-sdk-go/releases/tag/v0.4.0 done ✅
