### ISSUE TITLE
Move to apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by ritazh** [servicemeshinterface/smi-sdk-go#98]
As of Kubernetes 1.16, CRDs have been promoted to GA. 
SMI currently uses `apiextensions.k8s.io/v1beta1`, which is deprecated in 1.19 and will be removed in 1.22: kubernetes/kubernetes#82022.
- Update the CRD yaml
- Update docs with supported Kubernetes version 1.16+, so we can default to `apiextensions.k8s.io/v1`
- Need to document known issues/workaround if there are existing `apiextensions.k8s.io/v1beta1` CRDs for upgrade scenarios

**Comment by michelleN** [comment]
+1 to this.

You brought up a good question around the upgrade story in today's meeting. It is my understanding that `kubectl convert` would have been a good way to recommend users update the SMI CRDs but that is deprecated with 1.16. Would be helpful to either give users a script to help with updating the CRDs with the new api group OR ask users to update manually. I'm not sure how that impacts the resources themselves. I'd have to look a little further into that.
