### ISSUE TITLE
v1alpha1 TrafficSplit crd weight field validation

### ISSUE THREAD

**Issue by mateiidavid** [servicemeshinterface/smi-sdk-go#99]
Hi 👋 I was recently working on adding `OpenAPI` validation to existing crds in linkerd. For TrafficSplit I thought I'd come straight to the source so I took the validation schema as is from this repository (made sure to credit everything ofc 😄 ).

In linkerd `v1alpha1` is still in use. Throughout the code base (including tests) the `weight` field is parsed as a quantity string (e.g 200m, 300m, etc.). Because the `weight` field is a number type in the schema, it breaks backwards compatibility with [older versions](https://github.com/servicemeshinterface/smi-spec/blob/master/apis/traffic-split/v1alpha1/traffic-split.md#specification) that also allow quantity strings as a type. This made the integration test suite [fail](https://github.com/linkerd/linkerd2/pull/5573#discussion_r560604785) in this case.

I thought I would let you know about this, just in case. I fixed it by turning the field type into `x-kubernetes-int-or-string` (this still keeps the schema as structural afaik). I realise you'll be moving to `v1` soon so it might not be worth it to change it now, but perhaps it might be helpful when doing per-version schemas.

It's a small change so I'd also be happy to do it myself depending on what your chosen course of action is. Thank you!

**Comment by michelleN** [comment]
oh that's neat. I'd definitely be open to this change. cc/ @nicholasjackson
